export const employess = [
  {
    id: 1,
    name: 'Thacher',
    email: 'thymas0@google.ca',
    gender: 'Male',
    phone: '840-802-3428',
    company: 'Agivu',
    country: 'Armenia',
    date: '7/15/2022',
  },
  {
    id: 2,
    name: 'Odilia',
    email: 'obambury1@ning.com',
    gender: 'Female',
    phone: '528-425-9283',
    company: 'Gabvine',
    country: 'Chile',
    date: '6/9/2022',
  },
  {
    id: 3,
    name: 'Cesaro',
    email: 'cbarnewelle2@usnews.com',
    gender: 'Male',
    phone: '112-363-3767',
    company: 'Teklist',
    country: 'Iceland',
    date: '7/8/2022',
  },
  {
    id: 4,
    name: 'Murvyn',
    email: 'mmara3@is.gd',
    gender: 'Male',
    phone: '271-708-0939',
    company: 'Centidel',
    country: 'Togo',
    date: '1/24/2022',
  },
  {
    id: 5,
    name: 'Sonni',
    email: 'svanmerwe4@sciencedirect.com',
    gender: 'Female',
    phone: '732-700-0090',
    company: 'Browsebug',
    country: 'Ethiopia',
    date: '4/5/2022',
  },
  {
    id: 6,
    name: 'Orion',
    email: 'obrodley5@ca.gov',
    gender: 'Male',
    phone: '823-403-8824',
    company: 'Blogspan',
    country: 'China',
    date: '1/15/2022',
  },
  {
    id: 7,
    name: 'Rivkah',
    email: 'rhebditch6@nifty.com',
    gender: 'Female',
    phone: '261-821-3055',
    company: 'Tavu',
    country: 'Brazil',
    date: '8/8/2022',
  },
  {
    id: 8,
    name: 'Francisco',
    email: 'fwarbrick7@wikispaces.com',
    gender: 'Male',
    phone: '368-360-5985',
    company: 'Blogtags',
    country: 'Argentina',
    date: '1/20/2022',
  },
  {
    id: 9,
    name: 'Fredia',
    email: 'ftomsu8@rambler.ru',
    gender: 'Female',
    phone: '358-912-4846',
    company: 'Edgewire',
    country: 'Sweden',
    date: '9/13/2022',
  },
  {
    id: 10,
    name: 'Hammad',
    email: 'hfonzone9@linkedin.com',
    gender: 'Male',
    phone: '233-975-2104',
    company: 'Jaloo',
    country: 'Costa Rica',
    date: '5/3/2022',
  },
  {
    id: 11,
    name: 'Alecia',
    email: 'aolpina@parallels.com',
    gender: 'Female',
    phone: '696-992-5347',
    company: 'Myworks',
    country: 'Jordan',
    date: '8/31/2022',
  },
  {
    id: 12,
    name: 'Isobel',
    email: 'imoneyb@ed.gov',
    gender: 'Female',
    phone: '553-560-7541',
    company: 'Flashdog',
    country: 'China',
    date: '8/24/2022',
  },
  {
    id: 13,
    name: 'Rooney',
    email: 'rgansbuhlerc@edublogs.org',
    gender: 'Male',
    phone: '943-135-8217',
    company: 'Janyx',
    country: 'Poland',
    date: '10/9/2022',
  },
  {
    id: 14,
    name: 'Erick',
    email: 'econnochied@hp.com',
    gender: 'Male',
    phone: '185-922-7757',
    company: 'Youspan',
    country: 'Mauritius',
    date: '2/20/2022',
  },
  {
    id: 15,
    name: 'Garvy',
    email: 'gleidle@reddit.com',
    gender: 'Male',
    phone: '711-855-6906',
    company: 'Trunyx',
    country: 'China',
    date: '12/22/2022',
  },
  {
    id: 16,
    name: 'Phylys',
    email: 'pocurranf@mapquest.com',
    gender: 'Female',
    phone: '884-819-8205',
    company: 'Flashpoint',
    country: 'South Africa',
    date: '4/7/2022',
  },
  {
    id: 17,
    name: 'Lanita',
    email: 'lmacgilmarting@oracle.com',
    gender: 'Female',
    phone: '914-779-1301',
    company: 'Jabberbean',
    country: 'Indonesia',
    date: '5/16/2022',
  },
  {
    id: 18,
    name: 'Edgardo',
    email: 'econyersh@gnu.org',
    gender: 'Male',
    phone: '167-489-1718',
    company: 'Divavu',
    country: 'Russia',
    date: '5/25/2022',
  },
  {
    id: 19,
    name: 'Kevan',
    email: 'kwhittai@tripadvisor.com',
    gender: 'Male',
    phone: '916-933-2573',
    company: 'Trupe',
    country: 'China',
    date: '11/13/2022',
  },
  {
    id: 20,
    name: 'Ophelie',
    email: 'oladleyj@delicious.com',
    gender: 'Female',
    phone: '199-467-5868',
    company: 'Jaxspan',
    country: 'Philippines',
    date: '9/21/2022',
  },
  {
    id: 21,
    name: 'Bone',
    email: 'bmcilhaggak@exblog.jp',
    gender: 'Male',
    phone: '413-550-0648',
    company: 'Twinder',
    country: 'China',
    date: '7/13/2022',
  },
  {
    id: 22,
    name: 'Gale',
    email: 'geddisl@jigsy.com',
    gender: 'Female',
    phone: '160-591-4434',
    company: 'Vinte',
    country: 'Portugal',
    date: '1/14/2022',
  },
  {
    id: 23,
    name: 'Peter',
    email: 'pclaytonm@miitbeian.gov.cn',
    gender: 'Male',
    phone: '759-930-0578',
    company: 'Jabberbean',
    country: 'China',
    date: '7/6/2022',
  },
  {
    id: 24,
    name: 'Anneliese',
    email: 'alanden@1und1.de',
    gender: 'Genderfluid',
    phone: '366-274-2956',
    company: 'Chatterpoint',
    country: 'China',
    date: '8/29/2022',
  },
  {
    id: 25,
    name: 'Leslie',
    email: 'latkinsono@dailymotion.com',
    gender: 'Female',
    phone: '280-391-1915',
    company: 'Skyndu',
    country: 'New Zealand',
    date: '3/1/2022',
  },
  {
    id: 26,
    name: 'Brander',
    email: 'btaitp@privacy.gov.au',
    gender: 'Male',
    phone: '505-697-5934',
    company: 'Zava',
    country: 'Kazakhstan',
    date: '11/20/2022',
  },
  {
    id: 27,
    name: 'Hedy',
    email: 'hdurnianq@mapquest.com',
    gender: 'Female',
    phone: '910-852-0954',
    company: 'Trunyx',
    country: 'Colombia',
    date: '3/18/2022',
  },
  {
    id: 28,
    name: 'Donavon',
    email: 'dszymanekr@webmd.com',
    gender: 'Male',
    phone: '834-942-7173',
    company: 'Feedspan',
    country: 'Nigeria',
    date: '4/25/2022',
  },
];
